version: "3.8"

services:
  api:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${PORT}
    ports:
      - "4000:4000"