version: "3.8"

services:
  api:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - APP_PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"