# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  NODE_ENV: ${{ env.NODE_ENV }}
  AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  NODE_VERSION: '18.x'  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

       - uses: pnpm/action-setup@v2
         name: Install pnpm
         id: pnpm-install
         with:
          version: 7.28.0
          run_install: false 

      - name: Install dependencies
        run: pnpm install

      - name: Clean
        run: pnpm clean 

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Upload artifact for deployment job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ env.NODE_ENV }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'graphql-api-starter'
          slot-name: ${{ env.NODE_ENV }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5EEEE8DA37DC4DD29A9D53AC912443BA }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
